# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 09:00
from __future__ import unicode_literals

import raster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0035_remove_rastertile_rast'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastertile',
            name='rast',
            field=raster.fields.RasterFileField(blank=True, null=True, upload_to=b''),
        ),
    ]
