# -*- coding: utf-8 -*-
# Generated by Django 1.10.4.dev20161124100321 on 2016-11-28 10:40
from __future__ import unicode_literals

import raster.fields
import raster.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0036_rastertile_rast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastertile',
            name='rast',
            field=raster.fields.RasterFileField(blank=True, null=True, upload_to=raster.models.upload_tile_to),
        ),
    ]
