# -*- coding: utf-8 -*-
# Generated by Django 1.11.2.dev20170508150049 on 2017-05-09 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0037_auto_20161128_1040'),
        ('raster', '0037_auto_20170509_0559'),
    ]

    operations = [
    ]
