# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0038_auto_20171116_1027'),
        ('raster', '0038_merge_20170509_1003'),
    ]

    operations = [
    ]
