# Generated by Django 2.0.4 on 2018-04-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0038_merge_20170509_1003'),
        ('raster', '0038_auto_20171116_1027'),
    ]

    operations = [
    ]
