# Generated by Django 2.1.7 on 2019-03-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raster', '0039_auto_20190313_0728'),
        ('raster', '0039_merge_20171116_1051'),
    ]

    operations = [
    ]
